### ISSUE TITLE
Anaconda is more efficient in playbook.yaml

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat-lectures#1]
Replace all python packages (including basemap) by anaconda (Just like in Nansat TravicCI)

**Comment by akorosov** [comment]
Anaconda provides gdal that cannot read most of the required file formats. This issue must wait until we fix anaconda first (provide nersc_gdal package at Binstar).

**Comment by mortenwh** [comment]
Is this a relevant issue in this repository? I thought we would delete all
vagrant configs not in the nersc-vagrant repos?
