### ISSUE TITLE
Issue while creating new vagrant VM using windows 7 64 

### ISSUE THREAD

**Issue by philippelam** [nansencenter/nansat-lectures#5]
Hi,
 I tried to create a new VM using vagrant "course", on a windows 7-64 machine.  I got the following error message while provisioning (testing phase):
Best Regards,
Philippe

TASK [nansat : nansat | Nosetests] *********************************************

task path: /vagrant/provisioning/roles/nansat/tasks/nansat.yml:32
<192.168.33.11> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<192.168.33.11> EXEC /bin/sh -c '( umask 77 && mkdir -p "`echo $HOME/.ansible/t
mp/ansible-tmp-1473889556.72-17548293941933`" && echo ansible-tmp-1473889556.72
-17548293941933="`echo $HOME/.ansible/tmp/ansible-tmp-1473889556.72-17548293941
933`" ) && sleep 0'
<192.168.33.11> PUT /tmp/tmpbX1s59 TO /home/vagrant/.ansible/tmp/ansible-tmp-147
3889556.72-17548293941933/command
<192.168.33.11> EXEC /bin/sh -c 'LANG=en_US.UTF-8 GDAL_DATA=/home/vagrant/minico
nda/share/gdal LC_MESSAGES=en_US.UTF-8 PATH=/home/vagrant/miniconda/bin:/usr/sbi
n:/usr/bin:/sbin:/bin LC_ALL=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/
tmp/ansible-tmp-1473889556.72-17548293941933/command; rm -rf "/home/vagrant/.ans
ible/tmp/ansible-tmp-1473889556.72-17548293941933/" > /dev/null 2>&1 && sleep 0'

fatal: [192.168.33.11]: FAILED! => {"changed": true, "cmd": "nosetests nansat",
"delta": "0:00:02.362462", "end": "2016-09-14 21:45:59.200374", "failed": true,
"invocation": {"module_args": {"_raw_params": "nosetests nansat", "_uses_shell":
 true, "chdir": null, "creates": null, "executable": null, "removes": null, "war
n": true}, "module_name": "command"}, "rc": 1, "start": "2016-09-14 21:45:56.837
912", "stderr": "E\n============================================================
==========\nERROR: Failure: ImportError (/home/vagrant/miniconda/lib/python2.7/s
ite-packages/PyQt4/QtGui.so: undefined symbol: _ZN15QSessionManager16staticMetaO
bjectE)\n----------------------------------------------------------------------\
nTraceback (most recent call last):\n  File \"/home/vagrant/miniconda/lib/python
2.7/site-packages/nose/loader.py\", line 407, in loadTestsFromName\n    module =
 resolve_name(addr.module)\n  File \"/home/vagrant/miniconda/lib/python2.7/site-
packages/nose/util.py\", line 312, in resolve_name\n    module = __import__('.'.
join(parts_copy))\n  File \"/home/vagrant/miniconda/lib/python2.7/site-packages/
nansat/**init**.py\", line 24, in <module>\n    import matplotlib.pyplot as plt\
n  File \"/home/vagrant/miniconda/lib/python2.7/site-packages/matplotlib/pyplot.
py\", line 114, in <module>\n    _backend_mod, new_figure_manager, draw_if_inter
active, _show = pylab_setup()\n  File \"/home/vagrant/miniconda/lib/python2.7/si
te-packages/matplotlib/backends/__init__.py\", line 32, in pylab_setup\n    glob
als(),locals(),[backend_name],0)\n  File \"/home/vagrant/miniconda/lib/python2.7
/site-packages/matplotlib/backends/backend_qt4agg.py\", line 18, in <module>\n
  from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase\n
 File \"/home/vagrant/miniconda/lib/python2.7/site-packages/matplotlib/backends/
backend_qt5agg.py\", line 16, in <module>\n    from .backend_qt5 import QtCore\n
  File \"/home/vagrant/miniconda/lib/python2.7/site-packages/matplotlib/backends
/backend_qt5.py\", line 31, in <module>\n    from .qt_compat import QtCore, QtGu
i, QtWidgets, _getSaveFileName, __version__\n  File \"/home/vagrant/miniconda/li
b/python2.7/site-packages/matplotlib/backends/qt_compat.py\", line 137, in <modu
le>\n    from PyQt4 import QtCore, QtGui\nImportError: /home/vagrant/miniconda/l
ib/python2.7/site-packages/PyQt4/QtGui.so: undefined symbol: _ZN15QSessionManage
r16staticMetaObjectE\n\n--------------------------------------------------------
--------------\nRan 1 test in 0.004s\n\nFAILED (errors=1)", "stdout": "", "stdou
t_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

```
    to retry, use: --limit @provisioning/site.retry
```

PLAY RECAP *********************************************************************

192.168.33.11              : ok=27   changed=7    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by akorosov** [comment]
@philippelam , thank you for the note. Should be fixed in https://github.com/nansencenter/nersc-vagrant/commit/30b5237b3c1abb99a9183a9330e95043104b0ebe. Try to clone and run provisioning again.
